export const collections = [
  {
    id: 1,
    name: "Shadow Oversized Hoodie",
    price: 2499,
    sizes: ["S", "M", "L", "XL"],
    highlight: "Cyber streetwear essential",
    detail: "A premium oversized hoodie with soft fabric and a relaxed fit.",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7",
  },
  {
    id: 2,
    name: "Neon Black Jacket",
    price: 3999,
    sizes: ["M", "L", "XL"],
    highlight: "Perfect for night fits",
    detail: "A bold black jacket designed for modern street fashion.",
    image: "https://images.unsplash.com/photo-1520975954732-35dd22299614",
  },
  {
    id: 3,
    name: "Urban Cargo Pants",
    price: 2799,
    sizes: ["S", "M", "L", "XL"],
    highlight: "Utility meets comfort",
    detail: "Relaxed cargo pants with multiple pockets and clean styling.",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
  },
  {
    id: 4,
    name: "Minimal White Tee",
    price: 1199,
    sizes: ["S", "M", "L", "XL", "XXL"],
    highlight: "Clean everyday wear",
    detail: "A breathable cotton t-shirt for daily casual styling.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
  },
  {
    id: 5,
    name: "Midnight Denim Jacket",
    price: 3499,
    sizes: ["M", "L", "XL"],
    highlight: "Classic with a dark edge",
    detail: "A timeless denim jacket with a modern dark-wash finish.",
    image: "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef",
  },
  {
    id: 6,
    name: "Techwear Black Shirt",
    price: 1899,
    sizes: ["S", "M", "L"],
    highlight: "Sharp futuristic look",
    detail: "A structured black shirt made for clean cyber-inspired outfits.",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
  },
  {
    id: 7,
    name: "Oversized Graphic Tee",
    price: 1599,
    sizes: ["S", "M", "L", "XL"],
    highlight: "Statement street piece",
    detail: "An oversized printed tee made for bold everyday styling.",
    image: "https://images.unsplash.com/photo-1503341504253-dff4815485f1",
  },
  {
    id: 8,
    name: "Luxury Bomber Jacket",
    price: 4499,
    sizes: ["M", "L", "XL"],
    highlight: "Premium winter layer",
    detail: "A clean bomber jacket with a premium silhouette and warm finish.",
    image: "https://images.unsplash.com/photo-1523398002811-999ca8dec234",
  },
  {
    id: 9,
    name: "Relaxed Fit Sweatshirt",
    price: 2299,
    sizes: ["S", "M", "L", "XL"],
    highlight: "Soft, simple, powerful",
    detail: "A comfortable sweatshirt with a relaxed premium fit.",
    image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a",
  },
  {
    id: 10,
    name: "Black Formal Overshirt",
    price: 2999,
    sizes: ["M", "L", "XL", "XXL"],
    highlight: "Smart casual upgrade",
    detail: "A versatile overshirt that works for casual and semi-formal looks.",
    image: "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2",
  },
];